server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 1000
#    initialSize: 100
#    maxWait: 60000
#    minIdle: 500
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10


mybatis:
  type-aliases-package: com.example.springbootdemo04.mapper
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true





logging:
  level:
    com.example.springbootdemo04.mapper: debug